[build-system]
requires = ["setuptools", "pip >= 10"]
build-backend = "setuptools.build_meta"

[project]
name = "pysat"
version = "3.2.2"
description = "Supports science analysis across disparate data platforms"
readme = "README.md"
requires-python = ">=3.9"
license = {file = "LICENSE"}
authors = [
    {name = "Russell Stoneback, et al.", email = "pysat.developers@gmail.com"},
]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering :: Astronomy",
  "Topic :: Scientific/Engineering :: Physics",
  "Topic :: Scientific/Engineering :: Atmospheric Science",
  "License :: OSI Approved :: BSD License",
  "Natural Language :: English",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Operating System :: MacOS :: MacOS X",
  "Operating System :: POSIX :: Linux",
  "Operating System :: Microsoft :: Windows"
]
keywords = [
  "pysat",
  "ionosphere",
  "atmosphere",
  "thermosphere",
  "magnetosphere",
  "heliosphere",
  "observations",
  "models",
  "space",
  "satellites",
  "analysis"
]
dependencies = [
  "dask >= 2020.12.0",
  "netCDF4 >= 1.5.5.1",
  "numpy >= 1.19",
  "pandas >= 1.1.5",
  "portalocker >= 2.0",
  "pytest >= 6.2",
  "scipy >= 1.5.4",
  "toolz >= 0.11.1",
  "xarray >= 0.16.2"
]

[project.optional-dependencies]
test = [
  "flake8 >= 3.8.4",
  "flake8-docstrings >= 1.5",
  "hacking >= 1.0",
  "pysatSpaceWeather<0.1.0",
  "pytest-cov >= 2.10.1",
  "pytest-ordering >= 0.6"
]
doc = [
  "extras_require >= 0.2.3",
  "ipython >= 7.11",
  "m2r2 >= 0.2.7",
  "numpydoc >= 1.1",
  "readthedocs-sphinx-search==0.3.2",
  "sphinx >= 3.4.1",
  "sphinx_rtd_theme >= 1.2.2, < 2.0.0"
]

[project.urls]
Documentation = "https://pysat.readthedocs.io/en/latest/"
Source = "https://github.com/pysat/pysat"

[tool.coverage.report]
omit = ["*/instruments/templates/*"]

[tool.pytest.ini_options]
addopts = "--cov=pysat"
markers = [
  "all_inst",
  "download",
  "no_download",
  "load_options",
  "new_tests",
  "first",
  "second"
]
